version: '3'
services:
  web:
    # build: app/.
    image: openbookpublishers/img-mgr
    depends_on:
     - db
    ports:
     - "8080:8080"
    environment:
      PGHOST: db
      PGUSER: willwork
      PGNAME: starter
    depends_on:
      - db
    networks:
      local:
        ipv4_address: 172.20.0.3


  db:
    image: postgres:10
    restart: unless-stopped
    environment:
      POSTGRES_USER: willwork
      POSTGRES_DB: starter
    volumes:
      - db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - ./db:/docker-entrypoint-initdb.d
    networks:
      local:
        ipv4_address: 172.20.0.4

volumes:
  db:

networks:
  local:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/24
